# Generated by Django 5.0 on 2026-01-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, verbose_name='ID Пользователя')),
                ('url', models.TextField(verbose_name='Запрошенный URL')),
                ('reply_type', models.CharField(max_length=20, verbose_name='Тип (PDF/Video)')),
                ('status_code', models.IntegerField(verbose_name='Код ответа')),
                ('execution_time', models.FloatField(verbose_name='Время выполнения (сек)')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата/Время')),
            ],
            options={
                'verbose_name': 'Лог запроса',
                'verbose_name_plural': 'Логи запросов',
            },
        ),
    ]
