---
- name: reload nginx config
  become: yes
  become_user: "{{ app_user }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ getent_passwd[app_user].1 }}"
  command: "podman exec nginx nginx -s reload"
