---
- name: Создаем необходимые директории
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ app_dir }}" # папка для проекта
    - "/home/{{ deployer }}/.config/systemd/user" # папка для юнита systemd

- name: Регистрируемся в GHCR (репозиторий контейнеров от GitHub)
  containers.podman.podman_login:
    registry: ghcr.io
    username: "{{ ghcr_user }}"
    password: "{{ ghcr_token }}"

- name: Копирование юнит-файла и Docker-compose
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  loop:
    - { src: "app-stack.service.j2", dest: "/home/{{ deployer }}/.config/systemd/user/app-stack.service" }
    - { src: "{{ node_type }}-compose.yml", dest: "{{ app_dir }}/docker-compose.yml" }
    # node_type = masters/workers, переменная в group_vars
  #notify: "App_stack_manager - restart app stack"

- name: Копирование cookies для bot
  ansible.builtin.copy:
    src: "{{ lookup('env', 'HOME') }}/cookies.txt"
    dest: "{{ app_dir }}/cookies.txt"
    owner: "{{ deployer }}"
    group: "{{ deployer }}"
    mode: "0666"
  when: node_type == 'workers'



# НАСТРОЙКА БД (для мастера)
- name: Настройка БД для мастера
  when: node_type== 'masters'
  block:
    - name: Создаем папку для инициализации БД
      ansible.builtin.file:
        path: "{{ app_dir }}/init-db"
        state: directory
        owner: "{{ deployer }}"
        group: "{{ deployer }}"
        mode: "0755"

    - name: Копируем бэкап базы
      ansible.builtin.copy:
        src: "backup.sql" # поменять строчку когда будет готов бэкап базы
        dest: "{{ app_dir }}/init-db/backup.sql"
        owner: "{{ deployer }}"
        group: "{{ deployer }}"
        mode: "0644"


- name: Получить версию (тег) образа запущенного контейнера
  ansible.builtin.command: >
    podman inspect --format '{% raw %}{{ .Config.Image }}{% endraw %}' {{ container_name }}
  register: podman_image_info
  changed_when: false


- name: Вывести версию запущенного образа
  ansible.builtin.debug:
    msg: "Запущенный образ: {{ podman_image_info.stdout }}"


- name: Записать версию запущенного образа
  ansible.builtin.copy:
    content: "{{ podman_image_info.stdout }}"
    dest: "{{ app_dir }}/{{ container_name }}.current_version"
    mode: '0644'
  when: podman_image_info.rc == 0

- name: старт и healthcheck
  block:
  - name: рестарт сервиса (podman compose up + down)
    ansible.builtin.systemd:
      name: app-stack
      scope: user
      state: restarted
      enabled: true
      daemon_reload: true


  - name: Systemd is started
    ansible.builtin.systemd:
      name: app-stack
      state: started
      scope: user
      enabled: true
      daemon_reload: true


  - name: Ожидание container_name healthcheck
    containers.podman.podman_container_info:
      name: "{{ container_name }}"
    when: node_type == 'workers'
    register: container_info
    until:
      - container_info.containers | length > 0
      - container_info.containers[0].State.Health is defined
      - container_info.containers[0].State.Health.Status == "healthy"
    retries: 30
    delay: 10
    changed_when: false

  rescue: #Rollback
  - name: 🚨 Внимание! Деплой упал. Начинаем процесс Rollback.
    ansible.builtin.debug:
      msg: "Новая версия не прошла проверку здоровья. Читаем бэкап-файл стейта..."

  - name: Прочитать файл с предыдущим стабильным образом
    ansible.builtin.command: cat "{{ app_dir }}/{{ container_name }}.current_version"
    register: rollback_image
    failed_when: false
    changed_when: false

  - name: Копирование юнит-файла и Docker-compose
    ansible.builtin.template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      mode: "0644"
    loop:
      - { src: "app-stack.service.j2", dest: "/home/{{ deployer }}/.config/systemd/user/app-stack.service" }
      - { src: "{{ node_type }}-compose.yml", dest: "{{ app_dir }}/docker-compose.yml" }
    vars:
      image_name: "{{rollback_image}}"
    
  - name: рестарт сервиса (podman compose up + down)
    ansible.builtin.systemd:
      name: app-stack
      scope: user
      state: restarted
      enabled: true
      daemon_reload: true


  - name: Systemd is started
    ansible.builtin.systemd:
      name: app-stack
      state: started
      scope: user
      enabled: true
      daemon_reload: true


  - name: Ожидание container_name healthcheck
    containers.podman.podman_container_info:
      name: "{{ container_name }}"
    when: node_type == 'workers'
    register: container_info
    until:
      - container_info.containers | length > 0
      - container_info.containers[0].State.Health is defined
      - container_info.containers[0].State.Health.Status == "healthy"
    retries: 30
    delay: 10
    changed_when: false

  - name: Сообщить об успешном откате
    ansible.builtin.fail:
      msg: "Деплой новой версии завершился ошибкой, но система была успешно откатана на стабильный образ: {{ rollback_image_raw.stdout }}"


# МИГРАЦИИ (только для мастера)
- name: Применение миграций БД
  ansible.builtin.command: "podman exec master_web python manage.py migrate"
  register: app_stack_manager_migration_output
  until: app_stack_manager_migration_output.rc==0
  retries: 30
  delay: 10
  when: node_type == 'masters'
  run_once: true # это чтобы при запуске деплоя на нескольких нодах они все не ломанулись создавать миграции.
  changed_when: "'No migrations to apply' not in app_stack_manager_migration_output.stdout"
