# deploy/master/nginx.conf
events {
    worker_connections 1024;
}

http {
    # Объявляем зону лимитов (чтобы не упало)
    limit_req_zone $binary_remote_addr zone=mylimit:10m rate=10r/s;

    upstream bot_backend {
        server 192.168.56.11:5000;
    }

    server {
        listen 80;

        location / {
            return 403;
        }

        location /logs/ {
            proxy_pass http://web:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /admin/ {
            proxy_pass http://web:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /callbackA {
            limit_req zone=mylimit burst=10 nodelay;
            proxy_pass http://bot_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
