# Generated by Django 5.0 on 2026-01-06 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestlog',
            old_name='reply_type',
            new_name='request_type',
        ),
    ]
