name: app

networks:
  default:
    name: app_default

services:
  db:
    image: docker.io/library/postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=bot_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - default


  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
        #cap_drop:
        #- ALL
    environment:
      - DB_NAME=bot_db
      - DB_USER=admin
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
      - BOT_TOKEN=${BOT_TOKEN}
    networks:
      - default


  bot:
    build: .
    command: python SiteSender.py
    restart: always
    depends_on:
      - db
    tmpfs:
      - /tmp
        #cap_drop:
        #- ALL
    environment:
      - DB_NAME=bot_db
      - DB_USER=admin
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
      - BOT_TOKEN=${BOT_TOKEN}
      - MY_NODE_NAME=${MY_NODE_NAME}
      - YTDLP_JS_RUNTIME=node
#    volumes:      #убрать после отработки
#      - .:/code
    networks:
      - default


volumes:
  postgres_data:


