---
- name: обновление директории /app
  hosts: workers
  become: no

  tasks:
    - name: Копирование всех файлов проекта (Dockerfile, compose, py)
      copy:
        src: ../app/
        dest: "{{ app_dir }}/"

    - name: Перезапускаем контейнер с новыми файлами проекта
      shell: 'podman restart app_bot_1'
