- name: Деплой базы и админки
  hosts: masters
  #become: yes
  tasks:


    - name: Подготовка временной папки для Ansible под appuser
      file:
        path: "/home/appuser/.ansible/tmp"
        state: directory
        owner: appuser
        group: appuser
        mode: '0700' # Ansible сам поменяет на нужные через ACL
      become: yes


    - name: получаем информацию о UID прикладного пользователя appuser
      getent:
        database: passwd
        key: "{{ app_user }}"
    
  

    - name: задания, выполняемые от имени прикладного пользователя appuser
      become: yes
      become_user: "{{ app_user }}"
      environment:
        XDG_RUNTIME_DIR: "/run/user/{{ getent_passwd[app_user].1 }}"
      block:

    
      - name: Создаем папку для проекта
        file:
          path: "{{ app_dir }}"
          state: directory
          mode: "0755"


      - name: создание директории для пользовательских юнитов
        file:
          path: "/home/{{ app_user }}/.config/systemd/user"
          state: directory
          mode: "0755"


      - name: копирование юнит-файла для пользовательского сервиса
        template:
          src: "{{ playbook_dir }}/../deploy/master/app-stack.service.j2"
          dest: "/home/{{ app_user }}/.config/systemd/user/app-stack.service"
        register: systemd_unit


      - name: Копирование docker-compose.yml
        template:
          src: "{{ playbook_dir }}/../deploy/master/{{ item }}"
          dest: "{{ app_dir }}/"
        loop:
          - docker-compose.yml
            # - nginx.conf.j2
        register: compose_file


      - name: Копирование файлов проекта (Dockerfile, compose, py)
        copy:
          src: "{{ playbook_dir }}/../app/{{ item }}"
          dest: "{{ app_dir }}/"
        loop:
          - requirements.txt
          - Dockerfile
          - manage.py
          - logs
          - config


      - name: генерация и копирование nginx.conf
        template:
          src: "{{ playbook_dir }}/../deploy/master/nginx.conf.j2"
          dest: "{{ app_dir }}/nginx.conf"
        register: nginx_config
      
          
      - name: Создаем папку для инициализации БД
        file:
          path: "{{ app_dir }}/init-db"
          state: directory


      - name: Копируем бэкап базы
        copy:
          src: "{{ local_artifacts_dir }}/backup.sql"
          dest: "{{ app_dir }}/init-db/backup.sql"


      - name: Копируем готовые образы (артефакты) на Мастер
        copy:
          src: "{{ local_artifacts_dir }}/{{ item }}" 
          dest: "{{ app_dir }}/"
          mode: '0644'
        loop:
          - web_image.tar
          - nginx.tar

      - name: Проверяем, загружены ли образы
        command: "podman image exists {{ item }}"
        register: image_check
        ignore_errors: true
        changed_when: false
        loop:
          - web_image
          - nginx

      - name: Загружаем образы (только если их нет)
        command: "podman load -i {{ app_dir }}/{{ item.item }}.tar"
        when: item.rc != 0
        loop: "{{ image_check.results }}"
        register: load_result
        changed_when: "'Loaded image' in load_result.stdout"


      - name: перезагрузка конфигов systemd и запуск проекта
        systemd:
          name: app-stack
          scope: user
          state: started
          enabled: yes
          daemon_reload: yes
        when: systemd_unit.changed or compose_file.changed


      - name: Ожидание полной готовности стека
        shell: "systemctl --user is-active app-stack"
        register: app_status
        # Пытаемся 60 раз (по 10 секунд = 10 минут суммарно)
        until: app_status.stdout == "active"
        retries: 60
        delay: 10
        changed_when: false
        #become_user: "{{ app_user }}"
        #environment:
          #XDG_RUNTIME_DIR: "/run/user/{{ getent_passwd[app_user].1 }}"


      - name: Применение миграций БД
        shell: "podman exec master_web python manage.py migrate"
        retries: 30 
        delay: 10
        run_once: true # это чтобы при запуске деплоя на нескольких нодах они все не ломанулись создавать миграции.


      - name: Зачистка "висячих" образов (опционально)
        shell: "podman image prune -f"
        ignore_errors: yes


