[masters]
node-master ansible_host=192.168.88.40 ansible_user=vagrant

[workers_x86]
node-worker ansible_host=192.168.88.41 ansible_user=vagrant

[workers_arm]
arm-worker ansible_host=192.168.88.31 ansible_user=ildar ansible_ssh_private_key_file=/home/ildar/.ssh/id_rsa_rk3318/id_ed25519_rk3318 ansible_become_password="{{ vault_arm_password }}"


[workers:children]
workers_x86
workers_arm

[cluster:children]
masters
workers

[cluster:vars]
ansible_user=vagrant
ansible_ssh_private_key_file=~/devops-lab/.vagrant/machines/{{ inventory_hostname }}/virtualbox/private_key
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
