---
- name: "ОПИСАНИЕ: Что мы делаем"
  hosts: all              # На каких группах из инвентаря запускаем
  become: yes             # Нужны ли права sudo (обычно да)

  vars:                   # Сюда пишем переменные (пути, имена юзеров)
    my_var: "value"

  tasks:                  # Сами действия
    - name: "ШАГ 1: Описание действия"
      debug:              # Модуль (например: apt, copy, service, shell)
        msg: "Привет, это переменная {{ my_var }}"

    - name: "ШАГ 2: Установка чего-либо"
      apt:
        name: ufw
        state: present

